### ISSUE TITLE
Incorrect Assignment Multiplication

### ISSUE THREAD

**Issue by drocheam** [beltoforion/muparserx#107]
There's an error in the OprtAssignMul function (mpOprtBinAssign.cpp)

The line 191
`*pVar = cmplx_type(a*c-b*d, a*d-b*c); `

should be 
`*pVar = cmplx_type(a*c-b*d, a*d+b*c); `

Check https://www.math-only-math.com/multiplication-of-two-complex-numbers.html for reference.

**Comment by beltoforion** [comment]
should be fixed
