### ISSUE TITLE
Is it possible to directly represent a matrix instead of using many lines to define it?

### ISSUE THREAD

**Issue by AdrainT** [beltoforion/muparserx#124]
Hi, I want to evaluate the formula like "{{1,2,3}; {4,5,6}}*x", where x is a vector and {{1,2,3}; {4,5,6}} represents a 2 x 3 matrix. Here {{1,2,3}; {4,5,6}} can be replaced with any other formats. 
However, in the document, the only way I find to support this, is to use many lines like:

a = zeros(3,3);
a[0,0] = 1;
a[0,1] = 2;
a[0,2] = 3;
...
a[1,2] = 6;
a*x

This is very inconvenient, especially in interactive scenes. So I wonder whether we have a way to simply overcome this?

Thanks very much!

**Comment by beltoforion** [comment]
Unfortunately, there is no such feature but  you should be able to create a matrix constructor that takes a number of vectors and combines them into a matrix.

**Comment by AdrainT** [comment]
Thanks very much for your response! Do you mean that to accomplish this feature, I only need to add a  constructor for Matrix class that takes a number of vectors? Is there any other files I need to modify?

**Comment by beltoforion** [comment]
You need to write a custom parser function similar to zeros or eye that takes a number af vectors as input and creates a matrix out of this vectors,

**Comment by AdrainT** [comment]
Get it! Thanks so much!
