### ISSUE TITLE
Is matrix algebra in SetExpr possible?

### ISSUE THREAD

**Issue by joakimono** [beltoforion/muparserx#126]
I am trying to do matrix algebra in a `SetExpr`, but it throws an exception "_Can't evaluate function/operator "*": Array size mismatch._". The example below illustrates what I am trying to do. The value `y=A*x` works, but `SetExpr("A*x")` does not work.

Is this possible, or is additional implementation needed to achieve this?

```C
try {

    mup::ParserX parser(mup::pckALL_NON_COMPLEX);

    mup::Value x(3, 1, 0);
    x.At(0) = 1;
    x.At(1) = 2;
    x.At(2) = 3;

    mup::Value A(2, 3, 0);
    A.At(0, 0) = 1;
    A.At(1, 0) = 2;
    A.At(0, 1) = 3;
    A.At(1, 1) = 1;
    A.At(1, 2) = 4;

    mup::Value y = A*x;

    parser.DefineVar("x", mup::Variable(&x));
    parser.DefineVar("A", mup::Variable(&A));

    parser.SetExpr("A*x");
    mup::Value y2 = parser.Eval();

  } catch (mup::ParserError &e) {
    std::cout << e.GetMsg() << std::endl;
  }


```

**Comment by beltoforion** [comment]
No, not out of the box but there is nothing that prevents you from implementing it by connecting OprtMul up to a linear algebra system of your choice.

**Comment by joakimono** [comment]
I understand. Thank you for your prompt reply!
