### ISSUE TITLE
how to create a Loop Expression ? please a demo

### ISSUE THREAD

**Issue by 7812782** [beltoforion/muparserx#132]

**Comment by beltoforion** [comment]
Ther is no such thing in muparserx. It is not a programming language.

**Comment by 7812782** [comment]
I found the code snippet "if (sTok == _T("Loop"))" in the program, but I don't understand how to implement "Loop" using a conditional expression.

**Comment by beltoforion** [comment]
This feature is not implemented. It was a reserved keyword but has never been used.
