### ISSUE TITLE
`if-then-else` operator (proposal) 🆕

### ISSUE THREAD

**Issue by Victorcorcos** [beltoforion/muparserx#133]
## Proposal 💡 

Hello dear `muparserx` team ✋ 

Is there any chance to develop the `if-then-else` operator instead of the `?:` ternary operator?

For complex equations, using the `?:` ternary operator can be difficult to understand and debug, while using the `if-then-else` operator would be much more readable.

* With `?:` (current version)
```rb
5 > 3 ? "yes" : "no"
```

* With `if-then-else` (proposal)
```rb
if 5 > 3 then "yes" else "no"
```

## Attempt 🧗🏽‍♀️

I tried to make this change in `mpParserBase.cpp` replacing `?` → `then` and `:` → `else`. It work, but the `if` token is missing.

```diff
diff --git a/parser/mpParserBase.cpp b/parser/mpParserBase.cpp
index e20217c..27945f6 100644
--- a/parser/mpParserBase.cpp
+++ b/parser/mpParserBase.cpp
@@ -99,8 +99,8 @@ const char_type* ParserXBase::c_DefaultOprt[] = {
  _T("{"),
  _T("}"),
  _T(","),
- _T("?"),
- _T(":"),
+ _T("then"),
+ _T("else"),
  0 };
 
 //------------------------------------------------------------------------------
```

Then I ran `cmake CMakeLists.txt`, `make` and executed the `./example` file to see if it is working

```sh
$ ./example 
parsec> 5 > 3 then "yes" else "no"
Result (type: 's'):
ans = "yes"
```

Best regards,

**Comment by beltoforion** [comment]
Sorry, I don't plan any modifications regarding this issue. muparserx is not a programming language. If you really need if then else you are probably better of with just embedding python or lua because the feature requests wont stop at if-then-else.

**Comment by Victorcorcos** [comment]
I realize that muparserx isn't a full programming language, but in terms of functionality, its use of the `?:` conditional is already effective for handling conditions within equations. My intention here is simply to improve readability by replacing the `?:` conditional with an `if-then-else` (with backwards compatibility), not to suggest creating a programming language.

Great work on this library and thanks for your reply!

**Comment by beltoforion** [comment]
I'm closing the issue as i have no plans to alter or extend the syntax at the moment,
