### ISSUE TITLE
muparserx build system?

### ISSUE THREAD

**Issue by rashadkm** [beltoforion/muparserx#49]
Is there any plans on improving build system for muparserx? The current "just a makefile" is simple. But that itself forces to have clang or update Makefiles by hand. Even though I dont care for changing the makefile, the solution is not good interms of packaging or using another platform

cmake seems a good option as it is easy to configure and make on more platforms compared to other build tools.

I can provide a pull request, if that is acceptable ?

**Comment by martinrotter** [comment]
Hello, you have available project files for Qt Creator and Visual Studio. What would you want more? Cmake-based compilation script? Makefile is clean and purposed mainly for cland users, yes, but incorporating muparserx build process into build process of your own application is very simple.

**Comment by rashadkm** [comment]
Visual Studio is for windows only. remember same can be generated by cmake.
Qt creator is cross platform. But isnt that too much to have qt creator installed for installing muparserx.
I dont want to press the matter on cmake, or autobuild or QtCreator for that matter.

I was stating, it would be easier to maintain and for use some kind of cross platform. Having Qtcreator in muparserx itself stands for my point.

Yes. If I am bundling muparserx, the alright it is fine. But what If I need to package muparserx so that it can used by other using a linux or osx package manager?

I tried to package this for Fedora Linux. For that either I need to patch Makefile or add QtCreator as a dependency.

**Comment by martinrotter** [comment]
*.pro files are parsed by qmake utility, no need to actually have Qt Creator installed. It is hard to maintain 4 build types for this tiny project.

**Comment by rashadkm** [comment]
I understand the pain in maintaining mulitple build types. 

For me on fedora,

yum whatprovides /usr/bin/qmake-qt4 says:

1:qt-devel-4.8.5-10.fc20.i686 : Development files for the Qt toolkit
Dépôt               : fedora
Correspondance depuis :
Nom de fichier : /usr/bin/qmake-qt4 

So I need to add a dependency of qt-devel for creating linux packages, it will be a problem for package users to use muparserx. For myself, I dont care for that part..

Note, if you add cmake then you probably dont want to maintain, Makefile, visualstudio and maybe QtCreator

So, this enhancement will not be increasing the count and pain of build system supported by muparserx but rather reducing them.

**Comment by guruofquality** [comment]
I will second that. CMake is a worthy replacement for multiple build systems and its served me well for cross platform building and packaging. I have put together a CMakeLists.txt here and tested it on several machines:  https://github.com/pothosware/muparserx/commit/2304371e36cbd5148ed34f2c5e0992aec37efa4c

BTW, muparserx is a fantastic project. great work

**Comment by aaronpburke** [comment]
+1 for CMake.

**Comment by rashadkm** [comment]
FYI,
@guruofquality had a pull request for adding cmake and eventually closing this issue.
https://github.com/beltoforion/muparserx/pull/50

waiting for developers to merge this pull.

**Comment by beltoforion** [comment]
Code merged. I'm closing the issue. For details please see #50.
