### ISSUE TITLE
More assertions in parser/mpParserBase.cpp, line 1103

### ISSUE THREAD

**Issue by nasailja** [beltoforion/muparserx#59]
A couple more assertions remain from the batch I discovered with my first afl run, expressions `80>0?+:0` and `80>0?-:0` lead to `Assertion failed: (sidx>=0), function ParseFromRPN, file parser/mpParserBase.cpp, line 1103.` This is with muparserx that includes fixes for issues 55-58.

**Comment by beltoforion** [comment]
They seem pretty straightforward to fix. I'll probably also turn the assertions into an exception but i guess this would prevent you from finding more of the issues. The parser would then just throw an internal error. If you cant find any more I'll do that to be on the safe side.

**Comment by nasailja** [comment]
I think throwing would be better than asserting in any case as then I could provide a better error message.

**Comment by beltoforion** [comment]
Fixed in V4.0.2; Main parsing engine does no longer use assertions. You should always get an exception now.
