### ISSUE TITLE
Assertions from 0<01?1+:1 in parser/mpParserBase.cpp, line 1103

### ISSUE THREAD

**Issue by nasailja** [beltoforion/muparserx#60]
Latest git with parser in #55 asserts with following expressions: `0<01?1=:1` `0<01?1<:1` `0<01?1>:1` `0<01?1-:1` `0<01?1+:1` `0<01?1*:1` `0<01?1/:1` `0<01?1&:1` `0<01?1<<:1` `0<01?1>>:1`, reduced versions of ones found with afl. The 0 in 01 is required for the assert, as is 0<01 instead of 0>01 or 0=01.

**Comment by nasailja** [comment]
This also triggers the assert: `0<1?1!<1?1:1!=1+:1!=1`

**Comment by nasailja** [comment]
AFL has found about 60 unique crashes (for some definition of unique)(asserts probably) in muparserx from latest git so far. I suggest fixing asserts from currently known expressions and afterwards I can rerun the tests to see if any bugs survived.

**Comment by nasailja** [comment]
Another one: `{0<-0?1,-0/1,-0<-0,0,-0<-0,0:0<-0,0-0<-0,0}`

**Comment by beltoforion** [comment]
Fixed in V4.0.2; Main parsing engine does no longer use assertions. You should always get an exception now.
