### ISSUE TITLE
Segfaults with latest git

### ISSUE THREAD

**Issue by nasailja** [beltoforion/muparserx#61]
These expressions segfault the parser in #55 with mupx from latest git: `{?0:7m}-{7,-00007m}-{7M}`, `{{{?2},7:2}*7m}`, both in parser/mpParserBase.cpp:1158: `if (pStack[sidx--]->GetBool()==false)`

**Comment by beltoforion** [comment]
Fixed in V4.0.2; Main parsing engine does no longer use assertions. You should always get an exception now.
