### ISSUE TITLE
Support for Factorial

### ISSUE THREAD

**Issue by gang65** [beltoforion/muparserx#66]
It will be great to add factorial support:
https://en.wikipedia.org/wiki/Factorial

**Comment by beltoforion** [comment]
Factorial collides with the logical not operator. I'll leave the implementation to the client side.

**Comment by beltoforion** [comment]
Factorial collides with the logical not operator. It is part of muparserx but it is not automatically enabled. Just add the OprtFact operator if you need it but make sure you don't have the logical not at the same time.
