### ISSUE TITLE
Extend norm() to support matrix/vector

### ISSUE THREAD

**Issue by nasailja** [beltoforion/muparserx#67]
Looking at the code norm() seems to be supported only for complex variables but it would be handy also for matrix/vector expressions. For example as provided by octave/matlab/etc: http://octave.sourceforge.net/octave/function/norm.html Looks like mupx equivalent of p would be 0.5 for complex values. Being able to give p as an argument would also be nice.

**Comment by beltoforion** [comment]
It seems that matlab went a bit crazy with the norm function. This would require more time than just forwarding functionality of the standard library. Maybe later but at the moment chances are slim

**Comment by beltoforion** [comment]
closing the issue. no change planned
