### ISSUE TITLE
Assertion fails

### ISSUE THREAD

**Issue by jeffreyscottgraham** [beltoforion/muparserx#68]
The expression
(abs(-3)+2) >= min(6,5)

fails with
Assertion "stArgCount.size()" failed: parser/mpParserBase.cpp line 939

On Ubuntu Linux 14.04 x86_64 with g++ 4.9 and also on OSX with llvm, both with muparserx 4.0.5

**Comment by jeffreyscottgraham** [comment]
Noticed that by adding an outer pair of parens to the expression
((abs(-3)+2) >= min(6,5))

works

**Comment by beltoforion** [comment]
Fixed in Version 4.0.7
