### ISSUE TITLE
too many templates arguments for class template 'auto_ptr'

### ISSUE THREAD

**Issue by arivera12** [beltoforion/muparserx#74]
I have 2 errores when trying to compile and run the code

This is my test code

#include "mpParser.h"
#include "iostream"

using namespace mup;
using namespace std;
int main()
{
	ParserX  parser;
	parser.SetExpr("90^200");
	cout << parser.Eval();
}

I am using mac os x gcc compiler I don't really know if its a issue with the compiler....

This is the error message...

15:01:26 **** Build of configuration Debug for project Parser Tester ****
make all 
Building file: ../main.cpp
Invoking: GCC C++ Compiler
g++ -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"main.d" -MT"main.d" -o "main.o" "../main.cpp"
In file included from ../main.cpp:8:
In file included from ../mpParser.h:41:
In file included from ../mpParserBase.h:45:
In file included from ../mpIOprt.h:42:
In file included from ../mpICallback.h:43:
In file included from ../mpIToken.h:41:
In file included from ../mpTypes.h:50:
../mpCompat.h:47:11: warning: 'nullptr' macro redefined [-Wmacro-redefined]
  #define nullptr NULL
          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:87:9: note: previous definition is here
#define nullptr _VSTD::__get_nullptr_t()
        ^
In file included from ../main.cpp:8:
In file included from ../mpParser.h:41:
In file included from ../mpParserBase.h:46:
In file included from ../mpIValReader.h:40:
In file included from ../mpTokenReader.h:44:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stack:86:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:2268:9: error: too many template arguments for class template 'auto_ptr'
        unique_ptr<pointer, _Dp> __hold(
        ^                   ~~~~
../mpCompat.h:46:22: note: expanded from macro 'unique_ptr'
  #define unique_ptr auto_ptr
                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1945:29: note: template is declared here
class _LIBCPP_TYPE_VIS_ONLY auto_ptr
                            ^
In file included from ../main.cpp:8:
In file included from ../mpParser.h:41:
In file included from ../mpParserBase.h:46:
In file included from ../mpIValReader.h:40:
In file included from ../mpTokenReader.h:44:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stack:86:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/deque:2411:9: error: too many template arguments for class template 'auto_ptr'
        unique_ptr<pointer, _Dp> __hold(
        ^                   ~~~~
../mpCompat.h:46:22: note: expanded from macro 'unique_ptr'
  #define unique_ptr auto_ptr
                     ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:1945:29: note: template is declared here
class _LIBCPP_TYPE_VIS_ONLY auto_ptr
                            ^
1 warning and 2 errors generated.
make: *** [main.o] Error 1

15:01:27 Build Finished (took 696ms)

**Comment by guruofquality** [comment]
Its a c++11 codebase, try building with ``-std=c++11``

**Comment by arivera12** [comment]
I will give it a try right now!

**Comment by arivera12** [comment]
This fix the compiler issue but this library doesn't handle big numbers like this...

ParserX  parser;
parser.SetExpr("90^200");
cout << parser.Eval();

Sniff Sniff...
Thanks anyway...

**Comment by ArashPartow** [comment]
Just a quick note, the result for 90^200 as presented above is wrong. According to the ExprTk MPFR based REPL it is:

```
>> 90^200

result: 7.0550791086553325712464271575934796216507949612787315762871223209262085
55158293415657929852944713415815495233482535591186692979307182456669414508445453
52570279602853237603131924432833340880009999999999999999999999999999999999999999
999999999999999999999999999999999999999999999999999999999999999999999999999997e+
390
>>

```

Wolfram-Alpha seems to concurs:  https://www.wolframalpha.com/input/?i=90%5E200
