### ISSUE TITLE
Big numbers support?

### ISSUE THREAD

**Issue by arivera12** [beltoforion/muparserx#75]
I am using this lib [http://www.hvks.com](http://www.hvks.com/Numerical/arbitrary_precision.html) which supports big numbers with exact precision is there anyway to implements this lib over MuParserX? All the parsers that I found over the internet are using primitives datatypes and this is a big limitation when using any of this parser to do scientific emulations, test and calculations.

**Comment by beltoforion** [comment]
Sorry. I don't see a way to make muparserx work with custom types without major modifications.

**Comment by arivera12** [comment]
hmm ok I will then develop a parser from scratch to work with custom types that works with big ints and floats. All parsers over the web should been working with custom types and not primitive types cause is a big limitation of the std c and c++ default types. But thanks anyways. I will be submitting the new parser of my repo in the middles of September and October. Cheers!

**Comment by beltoforion** [comment]
You can have a look at atmsp. It does work with arbitrary precision numbers. (https://sourceforge.net/projects/atmsp/)

If you like to create something new anyway feel free to submit your parser to the math parser benchmark project (https://github.com/ArashPartow/math-parser-benchmark-project)

Kind Regards,
Ingo

**Comment by arivera12** [comment]
Thanks mate I will have a look.

Regards,
Anthony Rivera
