### ISSUE TITLE
User function with variadic arguments

### ISSUE THREAD

**Issue by ThirtySomething** [beltoforion/muparserx#84]
How to implement a user function with [variadic arguments](http://en.cppreference.com/w/cpp/language/variadic_arguments)? For example, we want to extend the parser with [arithmetic mean](https://en.wikipedia.org/wiki/Arithmetic_mean) and also with [geometric mean](https://en.wikipedia.org/wiki/Geometric_mean). Basically possible solutions are
```
ari(val_a, val_b)
geo(val_a, val_b)
```
But this is very unconvenient regarding more values. 
```
ari(ari(ari(ari(val_a, val_b),val_c),val_d),val_e)
geo(geo(geo(geo(val_a, val_b),val_c),val_d),val_e)
```
Any hints or proposals?

**Comment by beltoforion** [comment]
It's possible. Pleasehave a look at the implementation of the min/max or sum functions. Submit -1 to the ICallback constructor. Then use a_iArgc in the Eval function to obtain the actualnumber of parameters.

**Comment by ThirtySomething** [comment]
Perfect hint. Thanks a lot, solved our implementation.
