### ISSUE TITLE
How to update Auto Create Variables

### ISSUE THREAD

**Issue by adrianorocco** [beltoforion/muparserx#88]
Hi all,
just starting to use muparserx and i'm not able to deal with this issue. I receive expressions from an external module so I can't explicity create variables in my code. I set EnableAutoCreateVar = true and the evaluation works because the extern expressions are sort of " (xyz_abc = true) and (gty_pou = true) ". So i guess the parser internally create 2 variables "xyz_abc"  and "gty_pou" with the correct values. My problem is when the extern module send an update for a single variable e.g  gty_pou  = false. I'd like to tell the parser update gty_pou variable only but I can't understand how to access that variable given it is created with implicit variable definition. Thanks in advance

**Comment by martinrotter** [comment]
I am not sure if I understand your question correctly, but you want to:
1. Implicitly create and fill some variables with values.
2. Update values of those existing variables.

I am not sure where the problem is but this can be done simply by evaluating the "update" expression.

pseudocode
```
parser.EnableAutoCreateVar(true);
parser.SetExpr("aaa = true, bbb = false"); // implicitly define variables and set their values
parser.Eval();
parser.SetExpr("aaa = false"); // update value
parser.Eval();
```

**Comment by adrianorocco** [comment]
Hi,
i'd like to not revaluate the whole expressions.

parser.EnableAutoCreateVar(true);
parser.SetExpr("aaa = true and bbb = true"); // implicitly define variables and set their values
parser.Eval();
//parser.SetExpr("aaa = false"); // update value
// I want to change aaa = false
// and revaluate aaa = false and bbb = true the originale expression
// without submitting the whole expression again
parser.Eval();

**Comment by adrianorocco** [comment]
Maybe a more realistic example helps:

parser.EnableAutoCreateVar(true);
parser.SetExpr("ax = true and bx = true and cx = false and dx = true and ( ex = true or fx = false)"); 

// The parser internally create ax, bx, cx, dx, ex, fx and the bytecode for the whole expression tree.
// After the first evaluation only one variable change (e.g. cx = true)
// I want to re-eval the whole expression with cx updated
// I would'not want to  recall parser.SetExpr() with the whole expression again where only cx is changed

**Comment by martinrotter** [comment]
I do not think this is currently possible without second `SetExpr()` call. Correct me if I am wrong, @beltoforion.

**Comment by roalz** [comment]
Hi all,
I think I have a similar problem, mainly due to my poor understanding of how the library is supposed to work, and I can't find a suitable example in the doc or source code.

I have an input expression containing some variables that I don't know in advance, i.e.:
"(a * 3) > (b + 42)"

Thus I would like to use muParserX to provide me the list of variables it found in the expression ("a" and "b" in my example),
then ask my application user to input a value for each variable,
and update the variables values to the parser
and finally Eval() the expression completed with variable names.

Is there a way to do the above?
Or should I adopt a different approach?

Thanks

**Comment by beltoforion** [comment]
There is a function called GetExprVar which was specifically designed for that purpose. Have a look at:

const var_maptype& ParserXBase::GetExprVar() const

It will internally create the bytecode and build a list of all variables. You can then iterate over that list and define the variables. The return type is the same as for GetVar but of course it only returns the variables present in the expression and not the defined variables.

**Comment by adrianorocco** [comment]
Hello,
yep got through something similar using GetVar (i don't have any defined variable), removing assignements from the expression and dealing with void type returned during auto-assignement from the parser.
Seems to work actually but i would give a thought to provide a built in functionality ;)
Would be nice a public function like:
UpdateVariable(string name, Value val)
or something like that.
Thanks for help
