### ISSUE TITLE
Why not NOT?

### ISSUE THREAD

**Issue by Clon451** [beltoforion/muparserx#89]
This might not be a big issue but why is there no logical "not"?
"a xor true" isn't as nice as "not a" and I would even value xor less important than not.

**Comment by beltoforion** [comment]
Well that is strange, i was under the assumption there is one. Seems no one ever bothered to complain about it missing. Either that or it broke the parsing engine and i forgot about it.

**Comment by Wangzhike** [comment]
hope to support operator '!'

**Comment by beltoforion** [comment]
Since the operator may collide with a factorial operator i will not implement it.
