### ISSUE TITLE
Integer test causes floating point exceptions?

### ISSUE THREAD

**Issue by tepperly** [beltoforion/muparserx#98]
muparserx uses this code to test if a value is an integer:
```C++
  (val.imag() == 0) && (val.real() == (int)val.real())
```
If you enable floating point exceptions:
```C++
#include <fenv.h>
        feenableexcept(FE_INVALID | FE_DIVBYZERO);
```
the (val.real() == (int)val.real()) throws a floating point exception if you have a constant larger than what's representable as an integer (e.g., 1.0e13). This can make a lot of floating point exceptions that aren't the ones that I am really looking for.

A few stack exchange posts suggest:
```C++
   std::floor(val.real()) == val.real()
```
as a safer way to perform this check.

**Comment by beltoforion** [comment]
fixed as suggested
