### ISSUE TITLE
Assuming clang as the only compiler on Apple plaform.

### ISSUE THREAD

**Issue by atilag** [beltoforion/muparserx#99]
https://github.com/beltoforion/muparserx/blob/48887bde4f58f75edc1c1d37ffb0b011671ad183/CMakeLists.txt#L40

We support GNU g++ compiler in Apple platforms in our project and because MuparserX is one of our dependencies, it would be great if we can build with gcc on Apple as well.

An easy fix could be just remove these three lines:
```
#enable c++11 extensions for OSX
if (APPLE)
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x -Wc++11-extensions")
endif(APPLE)
```
Only pretty old versions of clang don't support "-std=c++11" flag. Do you still want to support them? If affirmative, a conditional like:

```
#enable c++11 extensions for OSX
if (APPLE AND CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++0x -Wc++11-extensions")
endif(APPLE)
```
... would be enough.

Thanks!

**Comment by beltoforion** [comment]
I do not need to support older versions of clang. If you submit this as a PR i will merge it.
